- ec2_remote_facts:
    region: eu-west-1
    filters:
      instance-state-name: running
      "tag:OpenshiftRole": Master
      "tag:OpenshiftCluster": "{{cluster_id}}"
  register: master_instance_facts

- ec2_remote_facts:
    region: eu-west-1
    filters:
      instance-state-name: running
      "tag:OpenshiftRole": Node
      "tag:OpenshiftCluster": "{{cluster_id}}"
  register: node_instance_facts


- name: Install Package
  package:
    name: java
    state: latest

- name: Add our inventory to the inventory file
  template:
    dest: "/bootstrap/ansible/openshift-inventory"
    src: 'openshift-inventory.j2'

- name: Clone Playbook
  git:
    repo: ssh://git@github.com/serene-wozniak/ansible-openshift-enterprise.git
    dest: /opt/openshift-ansible
    version: "master"
