- ec2_remote_facts:
    region: eu-west-1
    filters:
      instance-state-name: running
      "tag:OpenShiftRole": Master
      "tag:OpenShiftCluster": "{{cluster_id}}"
  register: master_instance_facts

- ec2_remote_facts:
    region: eu-west-1
    filters:
      instance-state-name: running
      "tag:OpenShiftRole": Node
      "tag:OpenShiftCluster": "{{cluster_id}}"
  register: node_instance_facts

- name: Add our inventory to the inventory file
  template:
    dest: "/bootstrap/ansible/openshift-inventory"
    src: 'openshift-inventory.j2'

- name: Clone Playbook
  git:
    repo: ssh://git@github.com/openshift/openshift-ansible.git
    dest: /opt/openshift-ansible
